project:
  type: website

website:
  title: "STA 702 Fall 2023"
  navbar:
    background: "#353148"
    align: center
    collapse-below: lg
  
    left:
      - href: index.qmd
        text: "{{< fa home >}} Home"
      - syllabus.qmd
      - schedule.qmd
      - resources.qmd
  repo-url: https://github.com/sta702-F23/website
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Merlise Clyde"
    background: "#353148"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
callout-appearance: simple 

execute: 
  freeze: auto
  
render:  
  - "*.qmd"
  - "_slides/*.Rmd"



