---
title: "{{< fa school-circle-check >}} Syllabus"
---

**When in doubt about anything at all, ask questions!!!**


### Prerequisites
ALL students are expected to be familiar with all the topics covered within the required prerequisites to be in this course. That is - mathematical statistics and probability, linear algebra, and multivariate calculus. Students are also expected to be familiar with R and are encouraged to learn LaTeX during the course.

### Workload

Work hours will include time spent going through the preassigned readings, attending lectures and lab sessions, and doing all graded work. 

### Graded Work

Graded work for the course will consist of homework assignments, lab exercises, two midterms and a final exam. Regrade requests for problem sets and lab exercises must be done via Gradescope AT MOST **24 hours** after grades are released! Regrade requests for quizzes, midterm, and final exams must be done via Gradescope AT MOST  **12 hours** after grades are released! Always write in complete sentences and show your steps.

Students' final grades will be determined as shown below:


Component             | Percentage
----------------------|----------------
Homework | 20%
Midterm | 20%
Midterm II | 20%
Lab exercises | 10%
Participation | 5%
Final Exam | 25%
: Component Percentage {.striped .hover}

There are no make-ups for any of the graded work except for medical or familial emergencies or for reasons approved by the instructor BEFORE the due date. See the instructor in advance of relevant due dates to discuss possible alternatives. 
	
Grades **may** be curved at the end of the semester. Cumulative averages of 90% -- 100% are guaranteed at least an A-, 80% -- 89% at least a B-, and 70% -- 79% at least a C-, however the exact ranges for letter grades will be determined at the end of the course.


### Descriptions of graded work

#### Problem sets
Homework will be handed out on a weekly basis. They will be based on both the lectures and labs and will be announced every Thursday or Friday -- be sure to check the website regularly!  Also, please note that any work that is not legible by the instructor or TAs will not be graded (given a score  of 0). Every write-up must be clearly written in full sentences and clear English. Any assignment that is completely unclear to the instructors and/or TAs, may result in a grade of a 0. For programming exercises, we will be using R/knitr with $\LaTeX$  for preparing assignments using github classroom for data analysis.

Each student MUST write up and turn in her or his own answers. You are encouraged to talk to each other regarding homework problems or to the instructor/TA. However, the write-up, solution, and code must be entirely your own work. No sharing of solutions or code!  The assignments must be submitted on [Gradescope](https://www.gradescope.com/courses/585736) under **Assignments**. Note that you will not be able to make online submissions after the due date, so be sure to submit before or by the Gradescope-specified deadline. You may resubmit, so when in doubt submit work early.  In certain situations if there are issues with submissions, the TA may review your GitHub repository prior to the due date.

Solutions will be curated from student solutions with proper attribution. Every week the TAs will select a representative correct solution for the assigned problems and put them together into one solutions set with each answer being attributed to the student who wrote it. If you would like to OPT OUT of having your homework solutions used for the class solutions, please let the Instructor and TAs know in advance.

**Finally, your lowest homework score will be dropped!**

#### Lab exercises
The objective of the lab assignments is to give you more hands-on experience with Bayesian data analysis. Attend the lab session and learn a concept or two and some R from the TA, and then work on the computational part of the problem sets. Each lab assignment should be submitted in timely fashion. You are REQUIRED to use R/knitr (or R/Rmarkdown in some cases).


#### Midterm Exams
There will be two inclass midterm exams.  Detailed instructions on the midterm will be made available later but please check dates on the calendar well in advance!

#### Final Exam
There will be a final exam after the reading week. If you miss any quiz or the midterm, your grade will depend more on the final exam score since there are no make-up exams. You cannot miss the final exam! Please check the important dates on the homepage for the date and time of the final before making plans to return home at the end of the semester. Detailed instructions on the final will be made available later.


### Late Submission Policy

- no late submission of homework or lab assignments, however we will drop the lowest score in each.

### Course Topics

-  Basics of Bayesian Models
-  Loss Functions, Inference and Decision Making
-  Predictive Distributions
-  Predictive Distributions and Model Checking
-  Bayesian Hypothesis Testing
-  Multiple Testing
-  MCMC (Gibbs & Metropolis Hastings Algorithms)
-  Bayesian Generalized Linear Models
-  Hiearchical Modeling and Random Effects
-  Hamiltonian Monte Carlo
-  NonParametric Bayes

For a detailed day-by-day list of topics, please refer to the [Course Schedule](schedule.html)


### Academic integrity
Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Citizens of this community commit to reflect upon and uphold these principles in all academic and nonacademic endeavors, and to protect and promote a culture of integrity.

Remember the Duke Community Standard that you have agreed to abide by:

> To uphold the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard):

> - I will not lie, cheat, or steal in my academic endeavors;
> - I will conduct myself honorably in all my endeavors; and
> - I will act if the Standard is compromised.

Cheating or plagiarism on any graded assessments, lying about an illness or absence and other forms of academic dishonesty are a breach of trust with classmates and faculty, violate the Duke Community Standard, and will not be tolerated. Such incidences will result in a 0 grade for all parties involved. Additionally, there may be penalties to your final class grade along with being reported to the Office of Student Conduct. Review the academic dishonesty policies at [https://studentaffairs.duke.edu/conduct/z-policies/academic-dishonesty](https://studentaffairs.duke.edu/conduct/z-policies/academic-dishonesty).


### Diversity & Inclusiveness
This course is designed so that students from all backgrounds and perspectives all feel welcome both in and out of class. Please feel free to talk to me (in person or via email) if you do not feel well-served by any aspect of this class, or if some aspect of class is not welcoming or accessible to you. My goal is for you to succeed in this course, therefore, let me know immediately if you feel you are struggling with any part of the course more than you know how to manage. Doing so will not affect your grades, but it will allow me to provide the resources to help you succeed in the course.

### Disability Statement
Students with disabilities who believe that they may need accommodations in the class are encouraged to contact the <a href="https://access.duke.edu/students/staff.php">Student Disabilities Access Office</a> at 919-668-1267 or <a href="mailto:disabilities@aas.duke.edu">disabilities@aas.duke.edu</a> as soon as possible to better ensure that such accommodations are implemented in a timely fashion.



### Other Information
It can be a lot more pleasant oftentimes to get one-on-one answers and help. Make use of the teaching team's office hours, we're here to help! Do not hesitate to talk to me during office hours or by appointment to discuss a problem set or any aspect of the course.  Questions related to course assignments and honesty policy should be directed to me. When the teaching team has announcements for you we will send an email to your Duke email address. Be sure to check your email daily.

Most of the course components will be held in person, but occasionally may need to be held online using Zoom meetings. If you have any concerns, issues or challenges, let the instructor know as soon as possible. Also, all students are strongly encouraged to rely on the forums in Sakai, for interacting among yourself and asking other students questions. You can also ask the instructor or the TAs questions on there and we will try to respond as soon as possible.  If you experience any technical issues with joining or using the forums, let the instructor know.


### Professionalism
Try as much as possible to refrain from texting or using your computer for anything other than coursework during class and labs. Again, the more engaged you are, the quicker you will be able to get through the materials. You are responsible for everything covered in the lecture videos, lecture notes/slides, and in the assigned readings.

