---
title: "Homework 6"
link-citations: true
toc: true
---



## Due: 11:59pm, Oct 24 (Note this is after the midterm)

This assignment has three main  types of problems - exercises that are starred and suggested to work as practice for the midterm, a theory problem you can delay until after the midterm, and a copmutational problem to also work on for lab after the midterm.

Please see [Gradescope](https://www.gradescope.com/courses/585736/assignments) for any updates on due dates.


## Getting started with Github Classroom

Go to Github classroom to  accept the invitation to create a repository for this assignment  at [HW6](https://classroom.github.com/a/tjojpmIi)
this will create a private repo in the STA702-F23 organization on Github with your github user name. Note: You may receive an email invitation to join STA702-F23 on your behalf. 

Hit refresh, to see the link for the repo, and then click on it to go to the STA702-F23 organization in Github.

Follow the instructions in the `README` in your repo and in the `hw*.Rnw` file to complete the assignment and
push to GitHub. If you encounter issues with Gradescope submission, it is critical
that you have pushed your final assignment to GitHub by the due date to validate timestamps.


## Gradescope Submission

You MUST submit both your final `.Rnw` and `.pdf` files to the repo on Github and upload the pdf to Gradescope here: [https://www.gradescope.com/courses/585736/assignments](https://www.gradescope.com/courses/585736/assignments)

Make sure to knit to pdf; ask the TA about knitting to pdf if you cannot figure it out. Be sure to submit under the right assignment entry by the due date!  


## Grading

Total: 20 points.
  