---
title: "Lecture 1: Basics of Bayesian inference"
---


## Readings:

- [A First Course in Bayesian Statistical Methods](https://find.library.duke.edu/catalog/DUKE004968562) by Peter D. Hoff.:
    + Section 1: Introduction and examples
    + Section 3.1: The binomial model 
    + Section 3.4: Discussion and further references




- [Bayesian Data Analysis (Third Edition)](https://find.library.duke.edu/catalog/DUKE006588051?utm_campaign=bento&utm_content=bento_result_link&utm_source=library.duke.edu&utm_medium=referral/) by Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin:
    + Section 1.1: The three steps of Bayesian data analysis
    + Section 1.2: General notation for statistical inference
    + Section 1.3: Bayesian inference
    + Section 1.9: Computation and software
    + Section 1.10: Bayesian inference in applied statistics
    + Section 2.1: Estimating a probability from binomial data
    + Section 2.2: Posterior as compromise between data and prior information
    + Section 2.4: Informative prior distributions



## Optional    
- [Bayesian Computation with R (Second Edition)](https://www.amazon.com/Bayesian-Computation-R-Use/dp/0387922970) by Jim Albert:
    + Section 2: Introduction to Bayesian thinking
