---
title: "Lecture 9: Gibbs Sampling and Data Augmentation"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Readings

- [A First Course in Bayesian Statistical Methods](https://find.library.duke.edu/catalog/DUKE004968562) by Peter D. Hoff
  + Chapter 6:  Posterior approximation with the Gibbs sampler
  + Section 9.1: The linear regression model (review)
  + Section 9.2: Bayesian estimation for a regression model
  + Section 10.4: Metropolis, Metropolis-Hastings and Gibbs
  + Section 10.5: Combining the Metropolis and Gibbs algorithm
  + Section 10.6: Discussion and further references
  + Section 12.1 Latent Variables for Ordinal Data
  



- [Bayesian Data Analysis (Third Edition)](https://find.library.duke.edu/catalog/DUKE006588051?utm_campaign=bento&utm_content=bento_result_link&utm_source=library.duke.edu&utm_medium=referral) by Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin
  + Section 11.1: Gibbs sampler
  + Section 11.2: Metropolis and Metropolis-Hastings algorithms 
  + Section 11.3: Using Gibbs and Metropolis as building blocks
  + Section 11.7: Bibliographic note
  + Section 14.1: Conditional modeling
  + Section 14.2: Bayesian analysis of the classical regression model

- [Albert & Chib](http://www.stat.cmu.edu/~brian/905-2009/all-papers/albert-chib-1993.pdf) Bayesian Analysis of Binary and Polychotomous Response Data, 
Journal of the American Statistical Association, Vol. 88, No. 422  pp. 669- 679
) 
- [The Bayesian Choice (Second Edition)](https://link-springer-com.proxy.lib.duke.edu/content/pdf/10.1007%2F0-387-71599-1.pdf)    by Christian Robert

    