---
title: "Lab 1: R Review and Monte Carlo"
toc: true
---

## Due: 11:00pm, Sunday, Sept 3


# Housekeeping

## R/RStudio

You all should have R and RStudio installed on your computers by now or access to the Department Server. If you do not and want to use your own computer, first install the latest version of R here: [https://cran.rstudio.com ](https://cran.rstudio.com) remember to select the right installer for your operating system). Next, install the latest version of RStudio here: [https://www.rstudio.com/products/rstudio/download/](https://www.rstudio.com/products/rstudio/download/). Scroll down to the "Installers for Supported Platforms" section and find the right installer for your operating system.

## R Knitr

You are required to use R knitr with the Rnw format to type up this lab report.  To get started see [basics](https://kbroman.org/knitr_knutshell/pages/latex.html) about knitr. Make sure to knit to `pdf` ; ask the TA about knitting to pdf if you cannot figure it out.


# Getting started

Go to Github classroom to create a repository for this assignment  at [lab1](https://classroom.github.com/classrooms/139913329-duke-statsci-sta-702-fall-2023)

This will create a private repo in the STA702-F23 organization on Github with your github user name. Note: You may receive an email invitation to join STA702-F23 on your behalf; please link your github account.

Hit refresh, to see the link for the repo, and then click on it to go to the STA702-F23 organization in Github.

Follow the instructions in the `README` in your repo and follow along in lab to complete the assignment. 

## Github Classroom 

You MUST submit both your final `.Rnw` and `.pdf` files to the repo on Github by the due date.

## Gradescope 

You must upload the final `pdf`  from your Github repo to [Gradescope](https://www.gradescope.com/courses/585736). 

Be sure to submit under the right assignment entry by the due date!


    