---
title: "Lab 0: Getting Started with R and Sweave/Knitr"
---

## Due: 11:00pm, Thursday, Aug  31


# Housekeeping

## R/RStudio

You all should have R and RStudio installed on your computers or feel free to use the Department servers. If you want a local version of RStudion,  first install the latest version of R here: https://cran.rstudio.com (remember to select the right installer for your operating system). Next, install the latest version of RStudio here: https://www.rstudio.com/products/rstudio/download/. Scroll down to the "Installers for Supported Platforms" section and find the right installer for your operating system.  You may also need to install `git` as well.

## Github

Create a github account if you do not have one here [https://github.com](https://github.com)

## R Sweave

You are required to use `R Sweave/knitr` to type up HW and lab reports.  Don't worry we will guide you along the way!

## Gradescope

You MUST submit the final `pdf` file to the course site on [Gradescope](https://www.gradescope.com/courses/585736).  Make sure to knit to pdf and  to submit under the right assignment entry.  

# Lab Goals

For the rest of this lab we are going to redirect you to Github.  At the end of this you should have

1. Cloned a repo based on instructions in the `README` file
2. Successfully create an `R Project` on your personal computer or a department server
3. Update a `Rnw` file with your info
4. Click `knitr` in Rstudio to create a pdf file!
5. Push to Github
6. Submit an assignment to [Gradescope](https://www.gradescope.com/courses/585736)


# Get Started!

1. Go to Github classroom to create a repository for [lab0](https://classroom.github.com/a/zqHyddy2)
This will create a private repo in the STA702-F23 organization on Github with your github user name. Note: You may receive an email invitation to join STA702-F23 on your behalf.  Please link your github user name to your profile.

2. Hit refresh, to see the link for the repo, and then click on it to go to the STA702-F23 organization in Github.

3. Follow the instructions in the `README` in your repo and follow along in lab to complete the assignment. 

Please try to carry this out before lab on Friday!


# Questions?

If you get stuck on any part - **please** ask a question in Sakai on the Ed Discussion forums!  Everyone can contribute to help (and part of participation points!)
