---
title: "Lab 6: Shrinkage Priors in Regression Comparison"
toc: true
---

## Due: 11:45AM, Mon Nov 6



# Getting started

Go to Github classroom to create a repository for this assignment  at [lab8](https://classroom.github.com/a/LbpyDl8A)

This will create a private repo in the STA702-F23 organization on Github with your github user name. Note: You may receive an email invitation to join STA702-F23 on your behalf; please link your github account.

Hit refresh, to see the link for the repo, and then click on it to go to the STA702-F23 organization in Github.

Follow the instructions in the `README` in your repo and follow along in lab to complete the assignment. 

## Github Classroom 

You MUST submit both your final `.Rnw` and `.pdf` files to the repo on Github by the due date.

## Gradescope 

You must upload the final `pdf`  from your Github repo to [Gradescope](https://www.gradescope.com/courses/585736). 

Be sure to submit under the right assignment entry by the due date!


    